version: '3'
services:
  db:
    image: postgres:13.0
    restart: on-failure
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=testpasswd
      - POSTGRES_USER=testuser
      - POSTGRES_DB=testdb
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      seoltab_net:
        ipv4_address: 172.16.25.2
  server:
    build:
      context: .
      dockerfile: ./dev.dockerfile
    ports:
      - '3000:3000'
    volumes:
      - '.:/usr/src/seoltab'
    depends_on:
      - db
    command: 'yarn start:prod'
    networks:
      seoltab_net:
        ipv4_address: 172.16.25.3
  test:
    build:
      context: .
      dockerfile: ./test.dockerfile
    ports:
      - '3000:3000'
    volumes:
      - '.:/usr/src/test'
    depends_on:
      - db
    command: 'yarn test'
    networks:
      seoltab_net:
        ipv4_address: 172.16.25.4
volumes:
  database:
networks:
  seoltab_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.25.0/24
